version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: todo_list
    ports:
      - "5432:5432"
  app:
    build: .
    depends_on:
      - db
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_NAME=todo_list
      - DB_HOST=db
    ports:
      - "8080:8080"
